from __future__ import annotations

import os
from pathlib import Path

import streamlit as st

from app_navigation import render_sidebar_nav

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_ROOT / ".env"

# Default values for reference
DEFAULT_CONFIG = {
    "OPENAI_API_KEY": "",
    "ALPHA_VANTAGE_API_KEY": "",
    "FMP_API_KEY": "",
    "TAVILY_API_KEY": "",
    "LANGSMITH_TRACING": "true",
    "LANGSMITH_ENDPOINT": "https://api.smith.langchain.com",
    "LANGSMITH_API_KEY": "",
    "LANGSMITH_PROJECT": "stock-bot-prod",
}


def load_env_file() -> dict[str, str]:
    """Load existing .env file if it exists."""
    env_vars: dict[str, str] = {}
    if ENV_FILE.exists():
        try:
            with ENV_FILE.open("r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    if "=" in line:
                        key, value = line.split("=", 1)
                        env_vars[key.strip()] = value.strip().strip('"').strip("'")
        except Exception as exc:
            st.error(f"Error reading .env file: {exc}")
    return env_vars


def save_env_file(env_vars: dict[str, str]) -> bool:
    """Save environment variables to .env file."""
    try:
        lines: list[str] = []
        lines.append("# Environment variables for Stock KB")
        lines.append("# This file is auto-generated by the Settings page")
        lines.append("")
        
        # Write API keys
        for key in ["OPENAI_API_KEY", "ALPHA_VANTAGE_API_KEY", "FMP_API_KEY", "TAVILY_API_KEY"]:
            value = env_vars.get(key, "")
            lines.append(f"{key}={value}")
        
        lines.append("")
        lines.append("# LangSmith Configuration")
        for key in ["LANGSMITH_TRACING", "LANGSMITH_ENDPOINT", "LANGSMITH_API_KEY", "LANGSMITH_PROJECT"]:
            value = env_vars.get(key, DEFAULT_CONFIG.get(key, ""))
            lines.append(f"{key}={value}")
        
        ENV_FILE.write_text("\n".join(lines), encoding="utf-8")
        return True
    except Exception as exc:
        st.error(f"Error saving .env file: {exc}")
        return False


def mask_key(key: str) -> str:
    """Mask API keys for display (show last 4 characters)."""
    if not key or len(key) < 4:
        return "••••••••"
    return "•" * (len(key) - 4) + key[-4:]


def render_settings_page():
    st.set_page_config(page_title="Stock KB - Settings", layout="wide")
    render_sidebar_nav()
    
    st.title("⚙️ Settings")
    st.caption("Configure your API keys and credentials")
    
    # Load existing values
    existing_env = load_env_file()
    
    # Also check Streamlit secrets (read-only, for display)
    secrets = {}
    if hasattr(st, "secrets"):
        try:
            secrets = {
                "OPENAI_API_KEY": st.secrets.get("OPENAI_API_KEY", ""),
                "ALPHA_VANTAGE_API_KEY": st.secrets.get("ALPHA_VANTAGE_API_KEY", ""),
                "FMP_API_KEY": st.secrets.get("FMP_API_KEY", ""),
                "TAVILY_API_KEY": st.secrets.get("TAVILY_API_KEY", ""),
                "LANGSMITH_API_KEY": st.secrets.get("LANGSMITH_API_KEY", ""),
            }
        except Exception:
            pass
    
    # Use existing .env values, fallback to secrets, then defaults
    current_values = {}
    for key in DEFAULT_CONFIG.keys():
        if key in existing_env:
            current_values[key] = existing_env[key]
        elif key in secrets and secrets[key]:
            current_values[key] = secrets[key]
        else:
            current_values[key] = DEFAULT_CONFIG.get(key, "")
    
    with st.form("settings_form", clear_on_submit=False):
        st.subheader("API Keys")
        
        col1, col2 = st.columns(2)
        
        with col1:
            openai_key = st.text_input(
                "OpenAI API Key",
                value=current_values.get("OPENAI_API_KEY", ""),
                type="password",
                help="Required for the main agent model",
            )
            alpha_vantage_key = st.text_input(
                "Alpha Vantage API Key",
                value=current_values.get("ALPHA_VANTAGE_API_KEY", ""),
                type="password",
                help="Required for market data",
            )
        
        with col2:
            fmp_key = st.text_input(
                "Financial Modeling Prep API Key",
                value=current_values.get("FMP_API_KEY", ""),
                type="password",
                help="Required for financial data",
            )
            tavily_key = st.text_input(
                "Tavily API Key",
                value=current_values.get("TAVILY_API_KEY", ""),
                type="password",
                help="Required for web search",
            )
        
        st.subheader("LangSmith Configuration")
        
        col3, col4 = st.columns(2)
        
        with col3:
            langsmith_tracing = st.selectbox(
                "Enable LangSmith Tracing",
                options=["true", "false"],
                index=0 if current_values.get("LANGSMITH_TRACING", "true") == "true" else 1,
                help="Enable tracing for debugging and monitoring",
            )
            langsmith_endpoint = st.text_input(
                "LangSmith Endpoint",
                value=current_values.get("LANGSMITH_ENDPOINT", DEFAULT_CONFIG["LANGSMITH_ENDPOINT"]),
                help="LangSmith API endpoint URL",
            )
        
        with col4:
            langsmith_key = st.text_input(
                "LangSmith API Key",
                value=current_values.get("LANGSMITH_API_KEY", ""),
                type="password",
                help="Optional: LangSmith API key for tracing",
            )
            langsmith_project = st.text_input(
                "LangSmith Project",
                value=current_values.get("LANGSMITH_PROJECT", DEFAULT_CONFIG["LANGSMITH_PROJECT"]),
                help="Project name for LangSmith traces",
            )
        
        submitted = st.form_submit_button("💾 Save Settings", type="primary", use_container_width=True)
        
        if submitted:
            new_env = {
                "OPENAI_API_KEY": openai_key.strip(),
                "ALPHA_VANTAGE_API_KEY": alpha_vantage_key.strip(),
                "FMP_API_KEY": fmp_key.strip(),
                "TAVILY_API_KEY": tavily_key.strip(),
                "LANGSMITH_TRACING": langsmith_tracing,
                "LANGSMITH_ENDPOINT": langsmith_endpoint.strip(),
                "LANGSMITH_API_KEY": langsmith_key.strip(),
                "LANGSMITH_PROJECT": langsmith_project.strip(),
            }
            
            if save_env_file(new_env):
                st.success("✅ Settings saved successfully! Restart the app for changes to take effect.")
                st.info("💡 Note: The app will reload environment variables on restart. Current session will continue using old values.")
            else:
                st.error("❌ Failed to save settings. Please check file permissions.")
    
    # Show current values (masked)
    with st.expander("📋 Current Configuration (masked)", expanded=False):
        st.caption("Current values from .env file and Streamlit secrets (masked for security)")
        
        display_env = load_env_file()
        if not display_env:
            display_env = {k: v for k, v in current_values.items() if v}
        
        if display_env:
            for key in ["OPENAI_API_KEY", "ALPHA_VANTAGE_API_KEY", "FMP_API_KEY", "TAVILY_API_KEY", "LANGSMITH_API_KEY"]:
                if key in display_env and display_env[key]:
                    st.text(f"{key}: {mask_key(display_env[key])}")
        else:
            st.info("No API keys configured yet.")
    
    st.markdown("---")
    st.caption("💡 Tip: API keys are saved to `.env` file in the project root. Make sure to add `.env` to `.gitignore` to keep your keys secure.")


if __name__ == "__main__":
    render_settings_page()

