"""Defines the state representation for the core principles extracting agent."""

import operator
from typing import TypedDict, Annotated
from langchain_core.documents import Document


class AgentState(TypedDict):
    """
    Represents the state of an agent in a simulation environment.

    Attributes:
        investor_name (str): the name of the investor associated with the ingested documents.
        documents (list[Document]): a list of documents ingested by the agent.
        core_principles (list[str]): a list of core principles extracted from the ingested documents.
        output (str): the final output generated by the agent.
    """

    investor_name: str
    documents: list[Document]
    core_principles: Annotated[list, operator.add]
    output: str
